import { StyleSheet } from "react-native";

import type { AppTheme } from "../theme";
import type { ThemeShadows } from "../shadows";
import {
  fontSize,
  fontStyle,
  homeChrome,
  lineHeight,
  radius,
  spacing,
} from "../tokens";

type StyleFactoryInput = {
  colors: AppTheme["colors"];
  surfaces: AppTheme["surfaces"];
  shadows: ThemeShadows;
};

export function createChromeStyles({
  colors,
  surfaces,
  shadows,
}: StyleFactoryInput) {
  return StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenPane: {
    flex: 1,
    backgroundColor: colors.background,
  },
  pagerPage: {
    flex: 1,
  },
  header: {
    paddingHorizontal: spacing.xl + 2,
    paddingBottom: spacing.md,
    marginBottom: spacing.xs,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logoLockup: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm + 1,
    flex: 1,
    minWidth: 0,
  },
  logoMark: {
    width: 36,
    height: 36,
    borderRadius: radius.md,
    backgroundColor: colors.accentDark,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.accent,
    ...shadows.subtle,
  },
  logoMarkText: {
    color: colors.onAccent,
    fontSize: fontSize.meta,
    ...fontStyle("bold"),
    letterSpacing: 0,
  },
  logo: {
    fontSize: fontSize.logo,
    ...fontStyle("bold"),
    color: colors.text,
    letterSpacing: 0,
  },
  logoAccent: {
    color: colors.accent,
    fontStyle: "italic",
  },
  subtitle: {
    color: colors.muted,
    marginTop: spacing.xs - 2,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.xl,
  },
  contentInner: {
    paddingBottom: homeChrome.navClearance,
  },
  contentInnerWithFab: {
    paddingBottom:
      homeChrome.fabBottomOffset +
      homeChrome.fabSize +
      homeChrome.fabScrollPaddingExtra,
  },
  heroCard: {
    backgroundColor: colors.hero,
    borderRadius: radius.md,
    padding: spacing.section,
    marginBottom: spacing.md + 2,
    ...shadows.card,
  },
  eyebrow: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("semibold"),
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  heroText: {
    marginTop: spacing.sm - 2,
    fontSize: fontSize.bodyLg,
    color: colors.muted,
    lineHeight: lineHeight.relaxed + 1,
  },
  heroMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.md,
    paddingTop: spacing.sm + 2,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  heroMetaText: {
    color: colors.muted,
    fontSize: fontSize.label,
    ...fontStyle("medium"),
  },
  metaDot: {
    width: spacing.xs,
    height: spacing.xs,
    borderRadius: spacing.xs / 2,
    backgroundColor: colors.muted,
  },
  primaryButton: {
    backgroundColor: colors.accent,
    paddingVertical: spacing.lg,
    borderRadius: radius.sm,
    alignItems: "center",
    marginBottom: spacing.section,
    borderWidth: 1,
    borderColor: colors.accentDark,
  },
  primaryButtonTight: {
    backgroundColor: colors.accent,
    paddingVertical: spacing.md + 1,
    borderRadius: radius.sm,
    alignItems: "center",
    marginBottom: spacing.md + 2,
    marginTop: 2,
    borderWidth: 1,
    borderColor: colors.accentDark,
  },
  primaryButtonCompact: {
    backgroundColor: colors.accent,
    paddingVertical: spacing.md + 2,
    borderRadius: radius.sm,
    alignItems: "center",
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: colors.accentDark,
  },
  primaryButtonText: {
    color: colors.onAccent,
    fontSize: fontSize.title,
    ...fontStyle("heavy"),
  },
  sectionTitle: {
    fontSize: fontSize.section,
    ...fontStyle("bold"),
    color: colors.text,
    marginBottom: spacing.xs + 1,
  },
  sectionTitleCompact: {
    fontSize: fontSize.sectionCompact,
    ...fontStyle("bold"),
    color: colors.text,
    marginBottom: spacing.sm + 2,
  },
  screenHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md + 2,
    marginBottom: spacing.lg,
  },
  inlinePrimaryButton: {
    backgroundColor: colors.accent,
    paddingHorizontal: spacing.section,
    minHeight: 42,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.accentDark,
  },
  inlinePrimaryButtonText: {
    color: colors.onAccent,
    fontSize: fontSize.label + 2,
    ...fontStyle("heavy"),
  },
  inlineSecondaryButton: {
    backgroundColor: colors.card,
    paddingHorizontal: spacing.lg,
    minHeight: 42,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  inlineSecondaryButtonText: {
    color: colors.accent,
    fontSize: fontSize.label + 2,
    ...fontStyle("bold"),
  },
  card: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    padding: spacing.section,
    marginBottom: spacing.md,
    ...shadows.card,
  },
  listGroup: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    marginBottom: spacing.section,
    overflow: "hidden",
    ...shadows.card,
  },
  plainListGroup: {
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    marginBottom: spacing.section,
    overflow: "visible",
  },
  listRow: {
    padding: spacing.section,
  },
  listSectionHeader: {
    paddingHorizontal: 2,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  plainListRow: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg - 1,
    marginBottom: spacing.sm + 2,
    paddingHorizontal: spacing.md + 1,
    paddingVertical: spacing.md - 1,
    ...shadows.subtle,
  },
  listRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: colors.rowBorder,
  },
  panel: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    padding: spacing.md + 3,
    marginBottom: spacing.section,
    ...shadows.card,
  },
  panelSecondary: {
    backgroundColor: colors.rowSurface,
    borderRadius: radius.sm,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  screenSectionTitle: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("bold"),
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: spacing.sm + 2,
    paddingHorizontal: spacing.xs,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  itemCopy: {
    flex: 1,
    minWidth: 0,
  },
  itemTitle: {
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    color: colors.text,
  },
  rowMetaText: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    marginTop: 2,
  },
  itemAmount: {
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("heavy"),
    color: colors.text,
    flexShrink: 0,
  },
  itemAmountStack: {
    alignItems: "flex-end",
    gap: spacing.xs,
    flexShrink: 0,
  },
  rowMetaLine: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: spacing.sm - 2,
    marginTop: 2,
  },
  rowMetaDivider: {
    color: colors.muted,
    fontSize: fontSize.meta,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: colors.accent,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 14,
  },
  secondaryButtonText: {
    color: colors.accentDark,
    ...fontStyle("semibold"),
  },
  emptyState: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    padding: spacing.section,
    marginBottom: spacing.section,
    ...shadows.card,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: fontSize.title,
    ...fontStyle("semibold"),
    marginBottom: spacing.sm - 2,
  },
  emptyStateButton: {
    marginTop: spacing.md,
    alignSelf: "flex-start",
    minHeight: 44,
    borderRadius: radius.md,
    backgroundColor: colors.accent,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm + 2,
    justifyContent: "center",
  },
  emptyStateButtonText: {
    color: colors.onAccent,
    fontSize: fontSize.body,
    ...fontStyle("semibold"),
  },
  bottomNav: {
    flexDirection: "row",
    alignItems: "flex-end",
    backgroundColor: colors.card,
    borderTopWidth: 0,
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.sm + 2,
    shadowColor: colors.accentDark,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 8,
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: spacing.sm,
    borderRadius: radius.sm,
    gap: spacing.xs - 1,
    minHeight: 44,
  },
  navItemPrimary: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: spacing.xs,
    marginTop: -spacing.lg,
    gap: spacing.xs,
    minHeight: 72,
  },
  navItemPrimaryButton: {
    width: 58,
    height: 58,
    borderRadius: radius.fab,
    backgroundColor: colors.accentLight,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    ...shadows.fab,
  },
  navItemPrimaryButtonActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accentDark,
  },
  navItemActive: {
    backgroundColor: colors.accentLight,
  },
  navText: {
    fontSize: 10,
    color: colors.muted,
    ...fontStyle("semibold"),
  },
  navTextActive: {
    color: colors.accentDark,
  },
  navTextPrimary: {
    fontSize: 11,
    color: colors.muted,
    ...fontStyle("bold"),
  },
  navTextPrimaryActive: {
    color: colors.accentDark,
  },
  fab: {
    position: "absolute",
    right: spacing.xl + 2,
    width: 56,
    height: 56,
    borderRadius: radius.fab,
    backgroundColor: colors.accent,
    borderWidth: 1,
    borderColor: colors.accentDark,
    alignItems: "center",
    justifyContent: "center",
    ...shadows.fab,
  },
  fabPressable: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  fabText: {
    color: colors.onAccent,
    fontSize: fontSize.label + 2,
    ...fontStyle("bold"),
  },
  pressed: {
    opacity: 0.72,
  },
  });
}
