import { StyleSheet } from "react-native";

import type { AppTheme } from "../theme";
import type { ThemeShadows } from "../shadows";
import {
  fontSize,
  fontStyle,
  lineHeight,
  radius,
  spacing,
} from "../tokens";

type StyleFactoryInput = {
  colors: AppTheme["colors"];
  surfaces: AppTheme["surfaces"];
  shadows: ThemeShadows;
};

export function createDashboardStyles({
  colors,
  surfaces,
  shadows,
}: StyleFactoryInput) {
  return StyleSheet.create({
  dashboardHeroCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.xl,
    marginBottom: spacing.lg,
    ...shadows.hero,
  },
  dashboardHeroFocus: {
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  dashboardHeroAmount: {
    textAlign: "center",
    marginTop: spacing.sm,
    letterSpacing: -1.2,
  },
  safeAmount: {
    fontSize: fontSize.display + 4,
    lineHeight: lineHeight.display + 4,
    ...fontStyle("heavy"),
    color: colors.text,
    marginTop: spacing.sm - 2,
  },
  dashboardHeroLabel: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("semibold"),
    textTransform: "uppercase",
    letterSpacing: 1.2,
    textAlign: "center",
  },
  dashboardHeroSubcopy: {
    marginTop: spacing.sm,
    fontSize: fontSize.body,
    color: colors.muted,
    lineHeight: lineHeight.body,
    ...fontStyle("regular"),
    textAlign: "center",
  },
  dashboardHeroStatusLine: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm - 1,
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: surfaces.dividerWarm,
  },
  dashboardHeroStatusText: {
    color: colors.accentDark,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight + 2,
    ...fontStyle("medium"),
    textAlign: "center",
  },
  dashboardCycleSnapshot: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md + 2,
    paddingBottom: spacing.md,
    marginBottom: spacing.xxl,
    ...shadows.subtle,
  },
  dashboardCycleSnapshotHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  dashboardCycleSnapshotTitle: {
    color: colors.text,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
  },
  dashboardCycleSnapshotDates: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    ...fontStyle("medium"),
    flexShrink: 1,
    textAlign: "right",
  },
  dashboardCycleSnapshotChipRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  dashboardCycleSnapshotChip: {
    flex: 1,
    minWidth: 0,
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.md - 1,
    borderWidth: 1,
    borderColor: surfaces.cardBorderSoft,
    alignItems: "center",
  },
  dashboardCycleSnapshotChipPressed: {
    backgroundColor: colors.warm,
    borderColor: surfaces.dividerWarm,
  },
  dashboardCycleSnapshotChipLabel: {
    color: colors.muted,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.tight - 3,
    ...fontStyle("medium"),
    textAlign: "center",
  },
  dashboardCycleSnapshotChipValue: {
    color: colors.text,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    marginTop: spacing.xs,
    textAlign: "center",
  },
  dashboardCycleSnapshotChipValueMuted: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    ...fontStyle("regular"),
  },
  dashboardCycleSnapshotChipHint: {
    color: colors.warmText,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.tight - 3,
    ...fontStyle("regular"),
    marginTop: spacing.xs - 1,
    textAlign: "center",
  },
  dashboardHeroReserveText: {
    color: colors.muted,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.tight - 2,
    marginTop: spacing.sm,
    ...fontStyle("regular"),
    textAlign: "center",
  },
  safeAmountSmall: {
    fontSize: fontSize.displaySm,
    lineHeight: lineHeight.displaySm,
    ...fontStyle("heavy"),
    color: colors.text,
    marginTop: spacing.sm,
  },
  dashboardSummaryPanel: {
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
    paddingVertical: spacing.sm + 2,
    paddingHorizontal: spacing.xs,
    marginBottom: spacing.xxl,
    ...shadows.subtle,
  },
  dashboardSummaryStrip: {
    flexDirection: "row",
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    marginBottom: 0,
    gap: 0,
  },
  dashboardSummaryItem: {
    flex: 1,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.sm,
    borderRadius: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
    minWidth: 0,
    alignItems: "center",
  },
  dashboardSummaryItemDivider: {
    borderRightWidth: 1,
    borderRightColor: surfaces.dividerWarm,
  },
  dashboardSummaryItemLast: {
    borderRightWidth: 0,
  },
  dashboardSummaryLabel: {
    color: colors.muted,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.tight - 3,
    ...fontStyle("medium"),
    textAlign: "center",
  },
  dashboardSummaryValue: {
    color: colors.warmText,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    marginTop: spacing.xs,
    textAlign: "center",
  },
  dashboardSummaryEmptyValue: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    ...fontStyle("regular"),
  },
  dashboardSectionHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: spacing.md,
    marginBottom: spacing.sm + 2,
  },
  dashboardSectionHint: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("semibold"),
  },
  comingUpCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    marginBottom: spacing.xxl + 2,
    ...shadows.card,
  },
  timelineList: {
    gap: 0,
  },
  timelineRow: {
    flexDirection: "row",
    minHeight: 68,
  },
  timelineRail: {
    width: 28,
    alignItems: "center",
    marginRight: spacing.sm,
  },
  timelineConnector: {
    width: 2,
    flex: 1,
    backgroundColor: surfaces.dividerWarm,
    minHeight: spacing.sm,
  },
  timelineConnectorSpacer: {
    flex: 1,
    minHeight: spacing.sm,
  },
  timelineNode: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineNodeIncome: {
    backgroundColor: colors.accentLight,
  },
  timelineNodeBill: {
    backgroundColor: colors.warning,
  },
  timelineNodeIcon: {
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight,
    ...fontStyle("bold"),
  },
  timelineRowMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingVertical: spacing.sm + 2,
    minWidth: 0,
  },
  timelineDateColumn: {
    width: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineDateMonth: {
    color: colors.muted,
    fontSize: fontSize.caption,
    ...fontStyle("semibold"),
    textTransform: "uppercase",
    letterSpacing: 0.5,
    lineHeight: lineHeight.tight - 3,
  },
  timelineDateDay: {
    color: colors.text,
    fontSize: fontSize.title,
    ...fontStyle("bold"),
    lineHeight: lineHeight.body,
    marginTop: 1,
  },
  timelineIncomeText: {
    color: colors.accentDark,
  },
  timelineBillText: {
    color: colors.warningText,
  },
  timelineIncomeAmount: {
    color: colors.accent,
  },
  timelineBillAmount: {
    color: colors.warningText,
  },
  dashboardTimelineCopy: {
    flex: 1,
    minWidth: 0,
  },
  dashboardTimelineTitle: {
    color: colors.text,
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
  },
  dashboardTimelineMeta: {
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    marginTop: spacing.xs - 1,
    ...fontStyle("medium"),
  },
  dashboardTimelineMetaIncome: {
    color: colors.accent,
  },
  dashboardTimelineMetaBill: {
    color: colors.warningText,
  },
  dashboardTimelineAmount: {
    minWidth: 84,
    textAlign: "right",
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("bold"),
    flexShrink: 0,
  },
  timelineEmptyText: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xs,
  },
  dashboardTimelineMoreText: {
    color: colors.accentDark,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight + 1,
    ...fontStyle("bold"),
  },
  dashboardTimelineFooter: {
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    marginTop: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    alignItems: "center",
  },
  dashboardBreakdownCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm + 2,
    marginBottom: spacing.md,
    ...shadows.card,
  },
  dashboardBreakdownCardCollapsed: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
  },
  dashboardBreakdownBody: {
    gap: spacing.md,
    paddingBottom: spacing.sm,
  },
  dashboardBreakdownSection: {
    gap: 0,
  },
  dashboardBreakdownSectionTitle: {
    color: colors.muted,
    fontSize: fontSize.caption,
    ...fontStyle("bold"),
    textTransform: "uppercase",
    letterSpacing: 0.8,
    lineHeight: lineHeight.tight,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },
  dashboardBreakdownToggleCollapsed: {
    borderTopWidth: 0,
    marginTop: 0,
  },
  dashboardBreakdownRow: {
    minHeight: 40,
    paddingVertical: spacing.sm + 2,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: surfaces.divider,
  },
  dashboardBreakdownTotalRow: {
    borderBottomWidth: 0,
    borderTopWidth: 1,
    borderTopColor: surfaces.dividerWarm,
    marginTop: spacing.xs,
    paddingTop: spacing.md + 2,
    paddingBottom: spacing.sm,
    minHeight: 48,
    alignItems: "center",
  },
  dashboardBreakdownSubtotalRow: {
    borderBottomWidth: 0,
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    marginTop: spacing.xs,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm + 2,
    minHeight: 44,
    alignItems: "center",
  },
  dashboardBreakdownLabel: {
    flex: 1,
    minWidth: 0,
    color: colors.muted,
    fontSize: fontSize.body,
    ...fontStyle("medium"),
    lineHeight: lineHeight.body,
  },
  dashboardBreakdownTotalLabel: {
    color: colors.text,
    fontSize: fontSize.bodyLg,
    ...fontStyle("semibold"),
  },
  dashboardBreakdownSubtotalLabel: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("semibold"),
  },
  dashboardBreakdownValue: {
    minWidth: 108,
    textAlign: "right",
    color: colors.text,
    fontSize: fontSize.bodyLg,
    ...fontStyle("bold"),
    lineHeight: lineHeight.body,
    fontVariant: ["tabular-nums"],
    flexShrink: 0,
  },
  dashboardBreakdownValueDeduction: {
    color: colors.warningText,
    ...fontStyle("semibold"),
  },
  dashboardBreakdownValueCredit: {
    color: colors.accent,
    ...fontStyle("semibold"),
  },
  dashboardBreakdownValueTotal: {
    color: colors.accent,
  },
  dashboardBreakdownTotalValue: {
    fontSize: fontSize.title + 1,
    ...fontStyle("bold"),
    color: colors.accentDark,
  },
  dashboardBreakdownSubtotalValue: {
    color: colors.text,
    ...fontStyle("bold"),
  },
  dashboardBreakdownRowLast: {
    borderBottomWidth: 0,
    paddingBottom: spacing.xs,
  },
  dashboardEnvelopeSwipeList: {
    marginBottom: spacing.md,
  },
  viewAllButton: {
    minHeight: 44,
    borderRadius: radius.lg,
    backgroundColor: colors.rowSurface,
    paddingHorizontal: spacing.md + 2,
    paddingVertical: spacing.sm + 2,
    marginBottom: spacing.section,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    minWidth: 132,
  },
  viewAllButtonText: {
    color: colors.accentDark,
    fontSize: fontSize.body,
    ...fontStyle("bold"),
  },
  viewAllButtonMeta: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("semibold"),
  },
  breakdownRow: {
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  compactBreakdownRow: {
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  breakdownLabel: {
    color: colors.muted,
    fontSize: fontSize.label,
  },
  breakdownValue: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("semibold"),
  },
  });
}
