import { StyleSheet } from "react-native";

import type { AppTheme } from "../theme";
import type { ThemeShadows } from "../shadows";
import {
  fontSize,
  fontStyle,
  lineHeight,
  radius,
  spacing,
} from "../tokens";

type StyleFactoryInput = {
  colors: AppTheme["colors"];
  surfaces: AppTheme["surfaces"];
  shadows: ThemeShadows;
};

export function createPaychecksStyles({
  colors,
  surfaces,
  shadows,
}: StyleFactoryInput) {
  return StyleSheet.create({
  paycheckSummaryPanel: {
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
    paddingVertical: spacing.sm + 2,
    paddingHorizontal: spacing.xs,
    marginBottom: spacing.lg,
    ...shadows.subtle,
  },
  paycheckSummaryStrip: {
    flexDirection: "row",
    gap: 0,
    marginBottom: 0,
  },
  paycheckSummaryItem: {
    flex: 1,
    minWidth: 0,
    backgroundColor: "transparent",
    borderRadius: 0,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.sm,
    alignItems: "center",
  },
  paycheckSummaryItemDivider: {
    borderRightWidth: 1,
    borderRightColor: surfaces.dividerWarm,
  },
  paycheckSummaryItemLast: {
    borderRightWidth: 0,
  },
  paycheckSummaryValue: {
    color: colors.warmText,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    marginTop: spacing.xs,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  paycheckSummaryValueHighlight: {
    color: colors.accent,
    fontSize: fontSize.bodyLg,
    ...fontStyle("bold"),
  },
  paycheckSummaryLabel: {
    color: colors.muted,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.tight - 2,
    ...fontStyle("medium"),
    textAlign: "center",
  },
  paycheckNextHeroSection: {
    marginBottom: spacing.lg,
  },
  paycheckNextHeroCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg + spacing.xs,
    paddingBottom: spacing.lg,
    ...shadows.hero,
  },
  paycheckNextHeroCardInner: {
    paddingBottom: spacing.xs,
  },
  paycheckNextHeroFocus: {
    alignItems: "center",
    gap: spacing.sm,
  },
  paycheckNextHeroStatusRow: {
    marginTop: spacing.xs,
  },
  paycheckNextHeroLabel: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("semibold"),
    textTransform: "uppercase",
    letterSpacing: 1.2,
    textAlign: "center",
  },
  paycheckNextHeroAmount: {
    color: colors.accent,
    textAlign: "center",
    marginTop: spacing.xs,
    letterSpacing: -1.2,
  },
  paycheckNextHeroSubcopy: {
    textAlign: "center",
    marginTop: spacing.sm,
  },
  paycheckNextHeroStatsBar: {
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: surfaces.dividerWarm,
  },
  paycheckNextHeroStatsLine: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight + 2,
    ...fontStyle("medium"),
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  paycheckNextHeroSwipeContainer: {
    marginHorizontal: -spacing.lg,
  },
  paycheckNextHeroSwipeForeground: {
    backgroundColor: surfaces.card,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xs,
    alignItems: "center",
  },
  paycheckCoverageLinkToggle: {
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    marginTop: spacing.sm,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 36,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  paycheckCoverageLinkText: {
    color: colors.accent,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight + 2,
    ...fontStyle("semibold"),
    textAlign: "center",
  },
  paycheckCoverageLinkTextPressed: {
    textDecorationLine: "underline",
  },
  paycheckSectionTitle: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("bold"),
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: spacing.sm + 2,
    paddingHorizontal: spacing.xs,
  },
  paycheckTimelineGroup: {
    marginBottom: spacing.section,
    gap: spacing.lg,
  },
  additionalIncomeGroup: {
    marginBottom: spacing.section,
    gap: spacing.sm,
  },
  additionalIncomeRow: {
    minHeight: 56,
    flexDirection: "column",
    alignItems: "stretch",
    gap: spacing.sm,
    overflow: "hidden",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
  },
  additionalIncomeRowReceived: {
    backgroundColor: surfaces.card,
  },
  additionalIncomeAmount: {
    color: colors.accent,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("bold"),
    fontVariant: ["tabular-nums"],
  },
  paycheckTimelineRow: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    overflow: "hidden",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg + spacing.xs,
    paddingBottom: spacing.lg,
    ...shadows.card,
  },
  paycheckTimelineRowExpected: {
    backgroundColor: surfaces.card,
  },
  paycheckTimelineRowReceived: {
    backgroundColor: colors.rowSurface,
  },
  paycheckRowHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  paycheckSwipeableContainer: {
    marginHorizontal: -spacing.lg,
  },
  paycheckSwipeableContainerAdditional: {
    marginHorizontal: -spacing.md,
  },
  paycheckSwipeableRowForeground: {
    minHeight: 72,
    backgroundColor: surfaces.card,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  paycheckSwipeableRowForegroundAdditional: {
    paddingHorizontal: spacing.md,
  },
  paycheckSwipeableRowForegroundRowSurface: {
    backgroundColor: colors.rowSurface,
  },
  paycheckTitleRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  paycheckAmountColumn: {
    alignItems: "flex-end",
    gap: spacing.sm,
    flexShrink: 0,
  },
  paycheckAmount: {
    color: colors.accent,
    fontSize: fontSize.title + 1,
    lineHeight: lineHeight.body,
    ...fontStyle("heavy"),
    fontVariant: ["tabular-nums"],
  },
  paycheckAmountReceived: {
    color: colors.warmText,
  },
  paycheckSectionToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm + 2,
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md - 1,
    minHeight: 44,
    ...shadows.subtle,
  },
  paycheckTimelineRowDivider: {
    borderBottomWidth: 0,
  },
  paycheckCoverageBlock: {
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    gap: spacing.md,
  },
  paycheckCoverageToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm + 2,
    minHeight: 44,
    paddingVertical: spacing.xs,
  },
  paycheckCoverageTitle: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight - 1,
    ...fontStyle("semibold"),
  },
  paycheckCoverageTotal: {
    color: colors.text,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight,
    ...fontStyle("bold"),
  },
  paycheckCoverageTotalRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  paycheckCoverageSummaryText: {
    color: colors.accentDark,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight - 1,
    ...fontStyle("semibold"),
  },
  paycheckCoverageRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.sm + 2,
  },
  paycheckCoverageName: {
    color: colors.text,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight,
    ...fontStyle("medium"),
  },
  paycheckCoverageAmount: {
    color: colors.text,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight,
    ...fontStyle("semibold"),
    flexShrink: 0,
    fontVariant: ["tabular-nums"],
    minWidth: 72,
    textAlign: "right",
  },
  paycheckCoverageExpanded: {
    gap: spacing.sm,
  },
  paycheckCoverageWindowText: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    ...fontStyle("medium"),
  },
  paycheckCoverageHelpText: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight + 2,
  },
  paycheckCoverageBillList: {
    gap: 0,
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    paddingTop: spacing.xs,
  },
  paycheckCoverageBillRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
    paddingVertical: spacing.md,
  },
  paycheckCoverageBillRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: surfaces.divider,
  },
  paycheckCoverageBillListTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.md,
    paddingTop: spacing.xs,
  },
  paycheckRecurrenceChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  paycheckCoverageSafeToSpendRow: {
    marginTop: spacing.xs - 1,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.rowBorder,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.sm + 2,
  },
  cycleSummaryCardCompact: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md + 2,
    marginBottom: spacing.md + 2,
    ...shadows.subtle,
  },
  cycleSummaryCardHero: {
    backgroundColor: surfaces.card,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    marginBottom: spacing.lg,
    ...shadows.card,
  },
  cycleSummaryCardTitle: {
    color: colors.text,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    marginBottom: spacing.xs,
  },
  cycleSummaryCardSummary: {
    color: colors.warmText,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight + 2,
    ...fontStyle("semibold"),
    fontVariant: ["tabular-nums"],
  },
  cycleSummaryCard: {
    backgroundColor: colors.card,
    borderRadius: radius.sm,
    padding: spacing.md + 2,
    marginBottom: spacing.md,
    ...shadows.subtle,
  },
  cycleAmount: {
    fontSize: 34,
    lineHeight: 40,
    ...fontStyle("heavy"),
    color: colors.text,
    marginTop: 8,
  },
  paycheckMetricRow: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  paycheckProjectionTotalRow: {
    marginTop: 12,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: colors.accentLight,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  paycheckProjectionTotalRowPrimary: {
    marginTop: spacing.sm,
    paddingTop: spacing.md + 2,
    borderTopWidth: 1,
    borderTopColor: surfaces.dividerWarm,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.md,
  },
  paycheckProjectionTotalLabel: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("semibold"),
    flex: 1,
  },
  paycheckProjectionTotalValue: {
    color: colors.accentDark,
    fontSize: fontSize.title + 1,
    ...fontStyle("bold"),
    fontVariant: ["tabular-nums"],
  },
  paycheckProjectionBreakdown: {
    gap: spacing.xs,
    paddingTop: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
  },
  paycheckProjectionBreakdownHelp: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight + 2,
  },
  paycheckProjectionCredit: {
    color: colors.accentDark,
  },
  paycheckProjectionDeduction: {
    color: colors.text,
  },
  paycheckCoveredBillsToggle: {
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
    alignItems: "center",
    minHeight: 36,
    justifyContent: "center",
  },
  paycheckBreakdownCaret: {
    color: colors.muted,
    fontSize: fontSize.title,
    lineHeight: lineHeight.body,
    ...fontStyle("bold"),
  },
  paycheckConfirmReceivedButton: {
    alignSelf: "stretch",
    minHeight: 40,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.accentLight,
    alignItems: "center",
    justifyContent: "center",
    marginTop: spacing.md,
  },
  paycheckAdditionalIncomeContent: {
    flex: 1,
    minWidth: 0,
    gap: spacing.sm,
  },
  });
}
