import { StyleSheet } from "react-native";

import { lightTheme, type AppTheme } from "./theme";

/** 4pt spacing grid — use these instead of one-off pixel values. */
export const spacing = {
  xs: 4,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  xxl: 24,
  section: 18,
  xxxl: 32,
} as const;

/** Corner radii — cards use lg/xl; chips and inputs use sm/md. */
export const radius = {
  sm: 10,
  md: 12,
  lg: 14,
  xl: 16,
  sheet: 18,
  fab: 27,
  pill: 999,
} as const;


/** Type scale — sizes and weights for consistent hierarchy. */
export const fontSize = {
  caption: 11,
  meta: 12,
  label: 13,
  body: 14,
  bodyLg: 16,
  title: 17,
  sectionCompact: 19,
  section: 23,
  logo: 23,
  displaySm: 38,
  display: 52,
} as const;

/** Inter faces loaded in app/_layout.tsx via @expo-google-fonts/inter. */
export const fontFamily = {
  regular: "Inter_400Regular",
  medium: "Inter_500Medium",
  semibold: "Inter_600SemiBold",
  bold: "Inter_700Bold",
  heavy: "Inter_800ExtraBold",
} as const;

export const fontWeight = {
  regular: "400",
  medium: "500",
  semibold: "600",
  bold: "700",
  heavy: "800",
} as const;

/** Prefer fontFamily over fontWeight — Inter uses discrete face files. */
export function fontStyle(weight: keyof typeof fontFamily = "regular") {
  return { fontFamily: fontFamily[weight] } as const;
}

export const lineHeight = {
  tight: 17,
  body: 20,
  relaxed: 22,
  displaySm: 44,
  display: 58,
} as const;

/** Home shell layout — bottom nav, FAB, and scroll clearance. */
export const homeChrome = {
  navClearance: 80,
  navContentHeight: 72,
  fabBottomOffset: spacing.xxxl * 2 + spacing.sm,
  fabSize: 56,
  fabScrollPaddingExtra: spacing.sm,
} as const;

export function getBottomNavHeight(bottomInset: number) {
  return (
    spacing.sm +
    2 +
    homeChrome.navContentHeight +
    Math.max(bottomInset, 10) +
    spacing.sm
  );
}

/** Distance from the screen bottom to the FAB's bottom edge. */
export function getFabBottom(bottomInset: number) {
  return getBottomNavHeight(bottomInset) + spacing.md;
}

/** Scroll content padding when the add-purchase FAB is visible. */
export function getFabScrollPadding(bottomInset: number) {
  return (
    getFabBottom(bottomInset) +
    homeChrome.fabSize +
    homeChrome.fabScrollPaddingExtra
  );
}

/** Reusable elevation presets — keep shadows subtle and on-brand. */
export function createShadows(theme: AppTheme) {
  const { colors } = theme;

  return {
    none: {
      shadowColor: "transparent",
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0,
      shadowRadius: 0,
      elevation: 0,
    },
    subtle: {
      shadowColor: colors.accentDark,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.025,
      shadowRadius: 5,
      elevation: 1,
    },
    card: {
      shadowColor: colors.accentDark,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 2,
    },
    raised: {
      shadowColor: colors.accentDark,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.07,
      shadowRadius: 12,
      elevation: 3,
    },
    hero: {
      shadowColor: colors.accentDark,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 20,
      elevation: 5,
    },
    fab: {
      shadowColor: colors.accentDark,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.16,
      shadowRadius: 12,
      elevation: 5,
    },
  } as const;
}

export type ThemeShadows = ReturnType<typeof createShadows>;

export function createStyles(theme: AppTheme) {
  const { colors, surfaces } = theme;
  const shadows = createShadows(theme);

  return StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenPane: {
    flex: 1,
    backgroundColor: colors.background,
  },
  pagerPage: {
    flex: 1,
  },
  header: {
    paddingHorizontal: spacing.xl + 2,
    paddingBottom: spacing.md,
    marginBottom: spacing.xs,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logoLockup: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm + 1,
    flex: 1,
    minWidth: 0,
  },
  logoMark: {
    width: 36,
    height: 36,
    borderRadius: radius.md,
    backgroundColor: colors.accentDark,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.accent,
    ...shadows.subtle,
  },
  logoMarkText: {
    color: colors.onAccent,
    fontSize: fontSize.meta,
    ...fontStyle("bold"),
    letterSpacing: 0,
  },
  logo: {
    fontSize: fontSize.logo,
    ...fontStyle("bold"),
    color: colors.text,
    letterSpacing: 0,
  },
  logoAccent: {
    color: colors.accent,
    fontStyle: "italic",
  },
  subtitle: {
    color: colors.muted,
    marginTop: spacing.xs - 2,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
  },
  content: {
    flex: 1,
    paddingHorizontal: spacing.xl,
  },
  contentInner: {
    paddingBottom: homeChrome.navClearance,
  },
  contentInnerWithFab: {
    paddingBottom:
      homeChrome.fabBottomOffset +
      homeChrome.fabSize +
      homeChrome.fabScrollPaddingExtra,
  },
  heroCard: {
    backgroundColor: colors.hero,
    borderRadius: radius.md,
    padding: spacing.section,
    marginBottom: spacing.md + 2,
    ...shadows.card,
  },
  dashboardHeroCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxl,
    paddingBottom: spacing.xl,
    marginBottom: spacing.lg,
    ...shadows.hero,
  },
  dashboardHeroFocus: {
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  dashboardHeroAmount: {
    textAlign: "center",
    marginTop: spacing.sm,
    letterSpacing: -1.2,
  },
  warningCard: {
    backgroundColor: colors.warning,
  },
  eyebrow: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("semibold"),
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  safeAmount: {
    fontSize: fontSize.display + 4,
    lineHeight: lineHeight.display + 4,
    ...fontStyle("heavy"),
    color: colors.text,
    marginTop: spacing.sm - 2,
  },
  dashboardHeroLabel: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("semibold"),
    textTransform: "uppercase",
    letterSpacing: 1.2,
    textAlign: "center",
  },
  dashboardHeroSubcopy: {
    marginTop: spacing.sm,
    fontSize: fontSize.body,
    color: colors.muted,
    lineHeight: lineHeight.body,
    ...fontStyle("regular"),
    textAlign: "center",
  },
  dashboardHeroStatusLine: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm - 1,
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: surfaces.dividerWarm,
  },
  dashboardHeroStatusText: {
    color: colors.accentDark,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight + 2,
    ...fontStyle("medium"),
    textAlign: "center",
  },
  dashboardCycleSnapshot: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md + 2,
    paddingBottom: spacing.md,
    marginBottom: spacing.xxl,
    ...shadows.subtle,
  },
  dashboardCycleSnapshotHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  dashboardCycleSnapshotTitle: {
    color: colors.text,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
  },
  dashboardCycleSnapshotDates: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    ...fontStyle("medium"),
    flexShrink: 1,
    textAlign: "right",
  },
  dashboardCycleSnapshotChipRow: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  dashboardCycleSnapshotChip: {
    flex: 1,
    minWidth: 0,
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.md - 1,
    borderWidth: 1,
    borderColor: surfaces.cardBorderSoft,
    alignItems: "center",
  },
  dashboardCycleSnapshotChipPressed: {
    backgroundColor: colors.warm,
    borderColor: surfaces.dividerWarm,
  },
  dashboardCycleSnapshotChipLabel: {
    color: colors.muted,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.tight - 3,
    ...fontStyle("medium"),
    textAlign: "center",
  },
  dashboardCycleSnapshotChipValue: {
    color: colors.text,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    marginTop: spacing.xs,
    textAlign: "center",
  },
  dashboardCycleSnapshotChipValueMuted: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    ...fontStyle("regular"),
  },
  dashboardCycleSnapshotChipHint: {
    color: colors.warmText,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.tight - 3,
    ...fontStyle("regular"),
    marginTop: spacing.xs - 1,
    textAlign: "center",
  },
  dashboardHeroReserveText: {
    color: colors.muted,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.tight - 2,
    marginTop: spacing.sm,
    ...fontStyle("regular"),
    textAlign: "center",
  },
  safeAmountSmall: {
    fontSize: fontSize.displaySm,
    lineHeight: lineHeight.displaySm,
    ...fontStyle("heavy"),
    color: colors.text,
    marginTop: spacing.sm,
  },
  warningText: {
    color: colors.warningText,
  },
  heroText: {
    marginTop: spacing.sm - 2,
    fontSize: fontSize.bodyLg,
    color: colors.muted,
    lineHeight: lineHeight.relaxed + 1,
  },
  heroMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.md,
    paddingTop: spacing.sm + 2,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  heroMetaText: {
    color: colors.muted,
    fontSize: fontSize.label,
    ...fontStyle("medium"),
  },
  metaDot: {
    width: spacing.xs,
    height: spacing.xs,
    borderRadius: spacing.xs / 2,
    backgroundColor: colors.muted,
  },
  primaryButton: {
    backgroundColor: colors.accent,
    paddingVertical: spacing.lg,
    borderRadius: radius.sm,
    alignItems: "center",
    marginBottom: spacing.section,
    borderWidth: 1,
    borderColor: colors.accentDark,
  },
  primaryButtonTight: {
    backgroundColor: colors.accent,
    paddingVertical: spacing.md + 1,
    borderRadius: radius.sm,
    alignItems: "center",
    marginBottom: spacing.md + 2,
    marginTop: 2,
    borderWidth: 1,
    borderColor: colors.accentDark,
  },
  primaryButtonCompact: {
    backgroundColor: colors.accent,
    paddingVertical: spacing.md + 2,
    borderRadius: radius.sm,
    alignItems: "center",
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: colors.accentDark,
  },
  primaryButtonText: {
    color: colors.onAccent,
    fontSize: fontSize.title,
    ...fontStyle("heavy"),
  },
  sectionTitle: {
    fontSize: fontSize.section,
    ...fontStyle("bold"),
    color: colors.text,
    marginBottom: spacing.xs + 1,
  },
  sectionTitleCompact: {
    fontSize: fontSize.sectionCompact,
    ...fontStyle("bold"),
    color: colors.text,
    marginBottom: spacing.sm + 2,
  },
  screenHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md + 2,
    marginBottom: spacing.lg,
  },
  inlinePrimaryButton: {
    backgroundColor: colors.accent,
    paddingHorizontal: spacing.section,
    minHeight: 42,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.accentDark,
  },
  inlinePrimaryButtonText: {
    color: colors.onAccent,
    fontSize: fontSize.label + 2,
    ...fontStyle("heavy"),
  },
  inlineSecondaryButton: {
    backgroundColor: colors.card,
    paddingHorizontal: spacing.lg,
    minHeight: 42,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  inlineSecondaryButtonText: {
    color: colors.accent,
    fontSize: fontSize.label + 2,
    ...fontStyle("bold"),
  },
  card: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    padding: spacing.section,
    marginBottom: spacing.md,
    ...shadows.card,
  },
  listGroup: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    marginBottom: spacing.section,
    overflow: "hidden",
    ...shadows.card,
  },
  plainListGroup: {
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    marginBottom: spacing.section,
    overflow: "visible",
  },
  listRow: {
    padding: spacing.section,
  },
  listSectionHeader: {
    paddingHorizontal: 2,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  plainListRow: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg - 1,
    marginBottom: spacing.sm + 2,
    paddingHorizontal: spacing.md + 1,
    paddingVertical: spacing.md - 1,
    ...shadows.subtle,
  },
  billRow: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.md,
    minHeight: 76,
  },
  billRowPaid: {
    backgroundColor: colors.rowSurface,
  },
  billRowPaused: {
    backgroundColor: colors.rowSurface,
  },
  billRowProjected: {
    backgroundColor: surfaces.card,
    borderWidth: 1,
    borderColor: surfaces.dividerWarm,
    ...shadows.subtle,
  },
  billRowEmpty: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    ...shadows.subtle,
  },
  billListGroup: {
    gap: spacing.lg,
  },
  billGroupedList: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    overflow: "hidden",
    marginBottom: spacing.lg,
    ...shadows.card,
  },
  billGroupedListRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: surfaces.divider,
  },
  billGroupedSwipeRow: {
    overflow: "hidden",
    borderRadius: 0,
    ...shadows.none,
  },
  billDateBadge: {
    width: 52,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: surfaces.timelineBadge,
    borderRadius: radius.md,
    paddingVertical: spacing.sm + 2,
    flexShrink: 0,
  },
  billDateBadgeDue: {
    backgroundColor: colors.accentLight,
  },
  billDateBadgePaid: {
    backgroundColor: colors.rowSurface,
  },
  billDateBadgeScheduled: {
    backgroundColor: colors.rowSurface,
  },
  billDateBadgePaused: {
    backgroundColor: colors.rowSurface,
  },
  billDateMonth: {
    color: colors.muted,
    fontSize: fontSize.caption,
    ...fontStyle("bold"),
    textTransform: "uppercase",
    letterSpacing: 0.6,
    lineHeight: lineHeight.tight - 3,
  },
  billDateMonthDue: {
    color: colors.accent,
  },
  billDateDay: {
    color: colors.text,
    fontSize: fontSize.title + 1,
    ...fontStyle("bold"),
    lineHeight: lineHeight.body,
    marginTop: spacing.xs,
    fontVariant: ["tabular-nums"],
  },
  billRowMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
    minWidth: 0,
  },
  billTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  billTitleText: {
    flex: 1,
    minWidth: 0,
  },
  billDueMeta: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    ...fontStyle("medium"),
  },
  billAmountColumn: {
    alignItems: "flex-end",
    justifyContent: "flex-start",
    flexShrink: 0,
    minWidth: 96,
  },
  billAmount: {
    color: colors.text,
    fontSize: fontSize.title,
    lineHeight: lineHeight.body,
    ...fontStyle("heavy"),
    fontVariant: ["tabular-nums"],
    textAlign: "right",
  },
  billAmountPaid: {
    color: colors.warmText,
  },
  billAmountDue: {
    color: colors.accent,
  },
  billSwipeableCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    overflow: "hidden",
    ...shadows.card,
  },
  billSwipeableRowForeground: {
    backgroundColor: surfaces.card,
    marginBottom: 0,
  },
  billsContentInner: {
    paddingBottom: homeChrome.navClearance + spacing.xl,
  },
  purchasesContentInner: {
    paddingBottom: homeChrome.navClearance + spacing.xl,
  },
  paycheckSummaryPanel: {
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
    paddingVertical: spacing.sm + 2,
    paddingHorizontal: spacing.xs,
    marginBottom: spacing.lg,
    ...shadows.subtle,
  },
  paycheckSummaryStrip: {
    flexDirection: "row",
    gap: 0,
    marginBottom: 0,
  },
  paycheckSummaryItem: {
    flex: 1,
    minWidth: 0,
    backgroundColor: "transparent",
    borderRadius: 0,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.sm,
    alignItems: "center",
  },
  paycheckSummaryItemDivider: {
    borderRightWidth: 1,
    borderRightColor: surfaces.dividerWarm,
  },
  paycheckSummaryItemLast: {
    borderRightWidth: 0,
  },
  paycheckSummaryValue: {
    color: colors.warmText,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    marginTop: spacing.xs,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  paycheckSummaryValueHighlight: {
    color: colors.accent,
    fontSize: fontSize.bodyLg,
    ...fontStyle("bold"),
  },
  paycheckSummaryLabel: {
    color: colors.muted,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.tight - 2,
    ...fontStyle("medium"),
    textAlign: "center",
  },
  paycheckNextHeroSection: {
    marginBottom: spacing.lg,
  },
  paycheckNextHeroCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg + spacing.xs,
    paddingBottom: spacing.lg,
    ...shadows.hero,
  },
  paycheckNextHeroCardInner: {
    paddingBottom: spacing.xs,
  },
  paycheckNextHeroFocus: {
    alignItems: "center",
    gap: spacing.sm,
  },
  paycheckNextHeroStatusRow: {
    marginTop: spacing.xs,
  },
  paycheckNextHeroLabel: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("semibold"),
    textTransform: "uppercase",
    letterSpacing: 1.2,
    textAlign: "center",
  },
  paycheckNextHeroAmount: {
    color: colors.accent,
    textAlign: "center",
    marginTop: spacing.xs,
    letterSpacing: -1.2,
  },
  paycheckNextHeroSubcopy: {
    textAlign: "center",
    marginTop: spacing.sm,
  },
  paycheckNextHeroStatsBar: {
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: surfaces.dividerWarm,
  },
  paycheckNextHeroStatsLine: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight + 2,
    ...fontStyle("medium"),
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  paycheckNextHeroSwipeContainer: {
    marginHorizontal: -spacing.lg,
  },
  paycheckNextHeroSwipeForeground: {
    backgroundColor: surfaces.card,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xs,
    alignItems: "center",
  },
  paycheckCoverageLinkToggle: {
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    marginTop: spacing.sm,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 36,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
  },
  paycheckCoverageLinkText: {
    color: colors.accent,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight + 2,
    ...fontStyle("semibold"),
    textAlign: "center",
  },
  paycheckCoverageLinkTextPressed: {
    textDecorationLine: "underline",
  },
  paycheckSectionTitle: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("bold"),
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: spacing.sm + 2,
    paddingHorizontal: spacing.xs,
  },
  paycheckTimelineGroup: {
    marginBottom: spacing.section,
    gap: spacing.lg,
  },
  additionalIncomeGroup: {
    marginBottom: spacing.section,
    gap: spacing.sm,
  },
  additionalIncomeRow: {
    minHeight: 56,
    flexDirection: "column",
    alignItems: "stretch",
    gap: spacing.sm,
    overflow: "hidden",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
  },
  additionalIncomeRowReceived: {
    backgroundColor: surfaces.card,
  },
  additionalIncomeAmount: {
    color: colors.accent,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("bold"),
    fontVariant: ["tabular-nums"],
  },
  paycheckTimelineRow: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    overflow: "hidden",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg + spacing.xs,
    paddingBottom: spacing.lg,
    ...shadows.card,
  },
  paycheckTimelineRowExpected: {
    backgroundColor: surfaces.card,
  },
  paycheckTimelineRowReceived: {
    backgroundColor: colors.rowSurface,
  },
  paycheckRowHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  paycheckSwipeableContainer: {
    marginHorizontal: -spacing.lg,
  },
  paycheckSwipeableContainerAdditional: {
    marginHorizontal: -spacing.md,
  },
  paycheckSwipeableRowForeground: {
    minHeight: 72,
    backgroundColor: surfaces.card,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
  },
  paycheckSwipeableRowForegroundAdditional: {
    paddingHorizontal: spacing.md,
  },
  paycheckSwipeableRowForegroundRowSurface: {
    backgroundColor: colors.rowSurface,
  },
  paycheckTitleRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  paycheckAmountColumn: {
    alignItems: "flex-end",
    gap: spacing.sm,
    flexShrink: 0,
  },
  paycheckAmount: {
    color: colors.accent,
    fontSize: fontSize.title + 1,
    lineHeight: lineHeight.body,
    ...fontStyle("heavy"),
    fontVariant: ["tabular-nums"],
  },
  paycheckAmountReceived: {
    color: colors.warmText,
  },
  paycheckSectionToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm + 2,
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
    marginTop: spacing.sm,
    marginBottom: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md - 1,
    minHeight: 44,
    ...shadows.subtle,
  },
  paycheckTimelineRowDivider: {
    borderBottomWidth: 0,
  },
  paycheckCoverageBlock: {
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    gap: spacing.md,
  },
  paycheckCoverageToggle: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm + 2,
    minHeight: 44,
    paddingVertical: spacing.xs,
  },
  paycheckCoverageTitle: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight - 1,
    ...fontStyle("semibold"),
  },
  paycheckCoverageTotal: {
    color: colors.text,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight,
    ...fontStyle("bold"),
  },
  paycheckCoverageTotalRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  paycheckCoverageSummaryText: {
    color: colors.accentDark,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight - 1,
    ...fontStyle("semibold"),
  },
  paycheckCoverageRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.sm + 2,
  },
  paycheckCoverageName: {
    color: colors.text,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight,
    ...fontStyle("medium"),
  },
  paycheckCoverageAmount: {
    color: colors.text,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight,
    ...fontStyle("semibold"),
    flexShrink: 0,
    fontVariant: ["tabular-nums"],
    minWidth: 72,
    textAlign: "right",
  },
  paycheckCoverageExpanded: {
    gap: spacing.sm,
  },
  paycheckCoverageWindowText: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    ...fontStyle("medium"),
  },
  paycheckCoverageHelpText: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight + 2,
  },
  paycheckCoverageBillList: {
    gap: 0,
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    paddingTop: spacing.xs,
  },
  paycheckCoverageBillRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: spacing.md,
    paddingVertical: spacing.md,
  },
  paycheckCoverageBillRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: surfaces.divider,
  },
  paycheckCoverageBillListTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.md,
    paddingTop: spacing.xs,
  },
  paycheckRecurrenceChipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  paycheckCoverageSafeToSpendRow: {
    marginTop: spacing.xs - 1,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.rowBorder,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.sm + 2,
  },
  listRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: colors.rowBorder,
  },
  rowActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  rowPrimaryAction: {
    alignSelf: "flex-start",
    minHeight: 36,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.accentLight,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 12,
  },
  rowPrimaryActionText: {
    color: colors.accentDark,
    fontSize: 13,
    ...fontStyle("heavy"),
  },
  rowPrimaryActionInline: {
    alignSelf: "flex-start",
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.accentLight,
    alignItems: "center",
    justifyContent: "center",
  },
  rowSecondaryActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  rowSecondaryActionButton: {
    minHeight: 30,
    paddingHorizontal: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  rowSecondaryActionText: {
    color: colors.muted,
    fontSize: 13,
    ...fontStyle("semibold"),
  },
  rowSecondaryDangerText: {
    color: colors.warningText,
  },
  rowActionButton: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.accentLight,
    backgroundColor: colors.card,
    alignItems: "center",
    justifyContent: "center",
  },
  rowActionButtonPrimary: {
    borderColor: colors.accent,
    backgroundColor: colors.accentLight,
  },
  rowActionButtonDanger: {
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  rowActionText: {
    color: colors.accentDark,
    fontSize: 13,
    ...fontStyle("semibold"),
  },
  rowActionDangerText: {
    color: colors.muted,
  },
  panel: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    padding: spacing.md + 3,
    marginBottom: spacing.section,
    ...shadows.card,
  },
  panelSecondary: {
    backgroundColor: colors.rowSurface,
    borderRadius: radius.sm,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  dashboardSummaryPanel: {
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
    paddingVertical: spacing.sm + 2,
    paddingHorizontal: spacing.xs,
    marginBottom: spacing.xxl,
    ...shadows.subtle,
  },
  dashboardSummaryStrip: {
    flexDirection: "row",
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    borderColor: "transparent",
    marginBottom: 0,
    gap: 0,
  },
  dashboardSummaryItem: {
    flex: 1,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.sm,
    borderRadius: 0,
    backgroundColor: "transparent",
    borderWidth: 0,
    minWidth: 0,
    alignItems: "center",
  },
  dashboardSummaryItemDivider: {
    borderRightWidth: 1,
    borderRightColor: surfaces.dividerWarm,
  },
  dashboardSummaryItemLast: {
    borderRightWidth: 0,
  },
  dashboardSummaryLabel: {
    color: colors.muted,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.tight - 3,
    ...fontStyle("medium"),
    textAlign: "center",
  },
  dashboardSummaryValue: {
    color: colors.warmText,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    marginTop: spacing.xs,
    textAlign: "center",
  },
  dashboardSummaryEmptyValue: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    ...fontStyle("regular"),
  },
  dashboardSectionHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: spacing.md,
    marginBottom: spacing.sm + 2,
  },
  dashboardSectionHint: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("semibold"),
  },
  comingUpCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    marginBottom: spacing.xxl + 2,
    ...shadows.card,
  },
  timelineList: {
    gap: 0,
  },
  timelineRow: {
    flexDirection: "row",
    minHeight: 68,
  },
  timelineRail: {
    width: 28,
    alignItems: "center",
    marginRight: spacing.sm,
  },
  timelineConnector: {
    width: 2,
    flex: 1,
    backgroundColor: surfaces.dividerWarm,
    minHeight: spacing.sm,
  },
  timelineConnectorSpacer: {
    flex: 1,
    minHeight: spacing.sm,
  },
  timelineNode: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineNodeIncome: {
    backgroundColor: colors.accentLight,
  },
  timelineNodeBill: {
    backgroundColor: colors.warning,
  },
  timelineNodeIcon: {
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight,
    ...fontStyle("bold"),
  },
  timelineRowMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingVertical: spacing.sm + 2,
    minWidth: 0,
  },
  timelineDateColumn: {
    width: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  timelineDateMonth: {
    color: colors.muted,
    fontSize: fontSize.caption,
    ...fontStyle("semibold"),
    textTransform: "uppercase",
    letterSpacing: 0.5,
    lineHeight: lineHeight.tight - 3,
  },
  timelineDateDay: {
    color: colors.text,
    fontSize: fontSize.title,
    ...fontStyle("bold"),
    lineHeight: lineHeight.body,
    marginTop: 1,
  },
  timelineIncomeText: {
    color: colors.accentDark,
  },
  timelineBillText: {
    color: colors.warningText,
  },
  timelineIncomeAmount: {
    color: colors.accent,
  },
  timelineBillAmount: {
    color: colors.warningText,
  },
  dashboardTimelineCopy: {
    flex: 1,
    minWidth: 0,
  },
  dashboardTimelineTitle: {
    color: colors.text,
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
  },
  dashboardTimelineMeta: {
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    marginTop: spacing.xs - 1,
    ...fontStyle("medium"),
  },
  dashboardTimelineMetaIncome: {
    color: colors.accent,
  },
  dashboardTimelineMetaBill: {
    color: colors.warningText,
  },
  dashboardTimelineAmount: {
    minWidth: 84,
    textAlign: "right",
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("bold"),
    flexShrink: 0,
  },
  timelineEmptyText: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xs,
  },
  dashboardTimelineMoreText: {
    color: colors.accentDark,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight + 1,
    ...fontStyle("bold"),
  },
  dashboardTimelineFooter: {
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    marginTop: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    alignItems: "center",
  },
  dashboardBreakdownCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm + 2,
    marginBottom: spacing.md,
    ...shadows.card,
  },
  dashboardBreakdownCardCollapsed: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
  },
  dashboardBreakdownBody: {
    gap: spacing.md,
    paddingBottom: spacing.sm,
  },
  dashboardBreakdownSection: {
    gap: 0,
  },
  dashboardBreakdownSectionTitle: {
    color: colors.muted,
    fontSize: fontSize.caption,
    ...fontStyle("bold"),
    textTransform: "uppercase",
    letterSpacing: 0.8,
    lineHeight: lineHeight.tight,
    paddingTop: spacing.xs,
    paddingBottom: spacing.sm,
  },
  dashboardBreakdownToggleCollapsed: {
    borderTopWidth: 0,
    marginTop: 0,
  },
  dashboardBreakdownRow: {
    minHeight: 40,
    paddingVertical: spacing.sm + 2,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: surfaces.divider,
  },
  dashboardBreakdownTotalRow: {
    borderBottomWidth: 0,
    borderTopWidth: 1,
    borderTopColor: surfaces.dividerWarm,
    marginTop: spacing.xs,
    paddingTop: spacing.md + 2,
    paddingBottom: spacing.sm,
    minHeight: 48,
    alignItems: "center",
  },
  dashboardBreakdownSubtotalRow: {
    borderBottomWidth: 0,
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    marginTop: spacing.xs,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm + 2,
    minHeight: 44,
    alignItems: "center",
  },
  dashboardBreakdownLabel: {
    flex: 1,
    minWidth: 0,
    color: colors.muted,
    fontSize: fontSize.body,
    ...fontStyle("medium"),
    lineHeight: lineHeight.body,
  },
  dashboardBreakdownTotalLabel: {
    color: colors.text,
    fontSize: fontSize.bodyLg,
    ...fontStyle("semibold"),
  },
  dashboardBreakdownSubtotalLabel: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("semibold"),
  },
  dashboardBreakdownValue: {
    minWidth: 108,
    textAlign: "right",
    color: colors.text,
    fontSize: fontSize.bodyLg,
    ...fontStyle("bold"),
    lineHeight: lineHeight.body,
    fontVariant: ["tabular-nums"],
    flexShrink: 0,
  },
  dashboardBreakdownValueDeduction: {
    color: colors.warningText,
    ...fontStyle("semibold"),
  },
  dashboardBreakdownValueCredit: {
    color: colors.accent,
    ...fontStyle("semibold"),
  },
  dashboardBreakdownValueTotal: {
    color: colors.accent,
  },
  dashboardBreakdownTotalValue: {
    fontSize: fontSize.title + 1,
    ...fontStyle("bold"),
    color: colors.accentDark,
  },
  dashboardBreakdownSubtotalValue: {
    color: colors.text,
    ...fontStyle("bold"),
  },
  dashboardBreakdownRowLast: {
    borderBottomWidth: 0,
    paddingBottom: spacing.xs,
  },
  purchaseCycleHeaderCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md + 2,
    marginBottom: spacing.md + 2,
    ...shadows.subtle,
  },
  cycleSummaryCardCompact: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md + 2,
    marginBottom: spacing.md + 2,
    ...shadows.subtle,
  },
  cycleSummaryCardHero: {
    backgroundColor: surfaces.card,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    marginBottom: spacing.lg,
    ...shadows.card,
  },
  cycleSummaryCardTitle: {
    color: colors.text,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    marginBottom: spacing.xs,
  },
  cycleSummaryCardSummary: {
    color: colors.warmText,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight + 2,
    ...fontStyle("semibold"),
    fontVariant: ["tabular-nums"],
  },
  screenSectionTitle: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("bold"),
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: spacing.sm + 2,
    paddingHorizontal: spacing.xs,
  },
  purchaseCycleHeaderTitle: {
    color: colors.text,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    marginBottom: spacing.xs,
  },
  purchaseCycleHeaderSummary: {
    color: colors.warmText,
    fontSize: fontSize.label,
    lineHeight: lineHeight.tight + 2,
    ...fontStyle("semibold"),
    fontVariant: ["tabular-nums"],
  },
  purchaseSummaryCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.xl,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md + 2,
    marginBottom: spacing.md + 2,
    ...shadows.raised,
  },
  purchaseSummaryGrid: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.md + 1,
  },
  purchaseSummaryMetric: {
    flex: 1,
    minWidth: 0,
    borderRadius: radius.md,
    backgroundColor: colors.rowSurface,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.sm + 2,
    alignItems: "center",
  },
  purchaseSummaryValue: {
    color: colors.warmText,
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    marginTop: spacing.xs,
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  purchaseSummaryValueHighlight: {
    color: colors.warningText,
    fontSize: fontSize.title,
    ...fontStyle("bold"),
  },
  purchaseSummaryLabel: {
    color: colors.muted,
    fontSize: fontSize.caption,
    lineHeight: lineHeight.tight - 3,
    ...fontStyle("semibold"),
    textAlign: "center",
  },
  purchaseSummaryCycleWindow: {
    color: colors.muted,
    fontSize: fontSize.meta,
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
  },
  purchaseBackToActiveCycleButton: {
    alignSelf: "flex-start",
    marginBottom: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.lg,
    backgroundColor: colors.rowSurface,
  },
  purchaseBackToActiveCycleText: {
    color: colors.accentDark,
    fontSize: fontSize.label,
    ...fontStyle("bold"),
  },
  purchaseCyclePickerButton: {
    minWidth: 96,
    maxWidth: 132,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    borderRadius: radius.lg,
    backgroundColor: colors.rowSurface,
    alignItems: "flex-end",
  },
  purchaseCycleSelectorBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    backgroundColor: colors.rowSurface,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md - 1,
    marginBottom: spacing.md,
    minHeight: 44,
    ...shadows.subtle,
  },
  purchaseCycleSelectorLabel: {
    flex: 1,
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("bold"),
  },
  purchaseCycleSelectorChevron: {
    color: colors.muted,
    fontSize: fontSize.label,
    ...fontStyle("bold"),
  },
  purchaseSummaryStripPanel: {
    backgroundColor: surfaces.card,
    borderRadius: radius.md,
    paddingVertical: spacing.sm + 2,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.lg,
    ...shadows.subtle,
  },
  purchaseSummaryStripText: {
    color: colors.warmText,
    fontSize: fontSize.label,
    ...fontStyle("semibold"),
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  purchaseCyclePickerLabel: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("bold"),
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  purchaseCyclePickerValue: {
    color: colors.text,
    fontSize: fontSize.label,
    ...fontStyle("bold"),
    marginTop: 2,
  },
  purchaseCycleOption: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    borderRadius: radius.lg,
    backgroundColor: colors.rowSurface,
    marginBottom: spacing.sm,
  },
  purchaseCycleOptionActive: {
    backgroundColor: colors.accentLight,
  },
  purchaseCycleOptionTitle: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("bold"),
  },
  purchaseCycleOptionMeta: {
    color: colors.muted,
    fontSize: fontSize.meta,
    marginTop: 2,
  },
  purchaseCycleOptionAmountBlock: {
    alignItems: "flex-end",
  },
  purchaseCycleOptionAmount: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("bold"),
  },
  purchaseCycleOptionSelected: {
    color: colors.accentDark,
    fontSize: fontSize.meta,
    ...fontStyle("bold"),
    marginTop: 2,
  },
  purchasePastCycleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    marginBottom: spacing.sm,
    ...shadows.subtle,
  },
  purchasePastCycleRowSelected: {
    backgroundColor: colors.accentLight,
  },
  purchasePastCycleSection: {
    marginTop: spacing.xl,
  },
  purchaseOutsideCycleSection: {
    gap: spacing.sm,
    marginTop: spacing.xl,
  },
  purchaseOutsideCycleMeta: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    paddingHorizontal: spacing.xs,
    marginBottom: spacing.sm,
  },
  purchasePreviousCycleGroup: {
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  purchasePreviousCycleRow: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    ...shadows.card,
  },
  purchasePreviousCycleHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
    marginBottom: spacing.sm,
  },
  purchasePreviousCycleTitle: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("bold"),
  },
  purchasePreviousCycleMeta: {
    color: colors.muted,
    fontSize: fontSize.meta,
    marginTop: 2,
  },
  purchasePreviousCycleAmount: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("bold"),
    fontVariant: ["tabular-nums"],
    flexShrink: 0,
  },
  purchasePreviousCycleExpanded: {
    marginTop: spacing.sm,
  },
  purchasePastCycleRowTitle: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("bold"),
  },
  purchasePastCycleRowMeta: {
    color: colors.muted,
    fontSize: fontSize.meta,
    marginTop: 2,
  },
  purchasePastCycleRowAmount: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("bold"),
    fontVariant: ["tabular-nums"],
  },
  purchaseUnassignedNotice: {
    marginTop: spacing.lg,
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md - 1,
    ...shadows.subtle,
  },
  purchaseUnassignedNoticeText: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
  },
  filterChipRow: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  filterChip: {
    minHeight: 36,
    paddingHorizontal: spacing.md + 2,
    borderRadius: radius.lg + 4,
    backgroundColor: colors.rowSurface,
    alignItems: "center",
    justifyContent: "center",
  },
  filterChipActive: {
    backgroundColor: colors.accentDark,
  },
  filterChipText: {
    color: colors.muted,
    fontSize: fontSize.label,
    ...fontStyle("bold"),
  },
  filterChipTextActive: {
    color: colors.onAccent,
  },
  transactionFeed: {
    marginBottom: spacing.md,
  },
  transactionDateGroup: {
    marginBottom: spacing.lg,
  },
  transactionDateHeader: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("bold"),
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.xs,
  },
  transactionListGroup: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    overflow: "hidden",
    marginBottom: 0,
    ...shadows.card,
  },
  purchaseSwipeableList: {
    gap: spacing.sm,
  },
  dashboardEnvelopeSwipeList: {
    marginBottom: spacing.md,
  },
  purchaseSwipeableCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    overflow: "hidden",
    ...shadows.card,
  },
  purchaseSwipeableRowForeground: {
    backgroundColor: surfaces.card,
  },
  envelopeSwipeableCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    overflow: "hidden",
    ...shadows.card,
  },
  envelopeSwipeableRowForeground: {
    backgroundColor: surfaces.card,
  },
  purchaseSwipeActions: {
    flexDirection: "row",
    alignItems: "stretch",
  },
  purchaseSwipeAction: {
    width: 76,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.sm,
    gap: spacing.xs,
  },
  purchaseSwipeActionAccent: {
    backgroundColor: colors.accentLight,
  },
  purchaseSwipeActionDefault: {
    backgroundColor: colors.soft,
  },
  purchaseSwipeActionDestructive: {
    backgroundColor: colors.warning,
  },
  purchaseSwipeActionIcon: {
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
  },
  purchaseSwipeActionLabel: {
    color: colors.accentDark,
    fontSize: fontSize.caption,
    ...fontStyle("semibold"),
    lineHeight: lineHeight.tight,
    textAlign: "center",
  },
  purchaseSwipeActionLabelDestructive: {
    color: colors.warningText,
  },
  purchaseTransactionRow: {
    minHeight: 76,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  purchaseRowMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md,
    minWidth: 0,
  },
  transactionRow: {
    minHeight: 56,
    paddingHorizontal: spacing.md + 1,
    paddingVertical: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  transactionRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: surfaces.divider,
  },
  transactionTitle: {
    color: colors.text,
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
  },
  transactionAmountStack: {
    alignItems: "flex-end",
    justifyContent: "center",
    gap: spacing.xs,
    flexShrink: 0,
  },
  transactionAmount: {
    color: colors.warningText,
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("heavy"),
  },
  purchaseTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.sm,
  },
  purchaseTitleText: {
    flex: 1,
    minWidth: 0,
  },
  purchaseAmountColumn: {
    alignItems: "flex-end",
    justifyContent: "flex-start",
    flexShrink: 0,
    minWidth: 96,
  },
  purchaseAmount: {
    color: colors.accent,
    fontSize: fontSize.title,
    lineHeight: lineHeight.body,
    ...fontStyle("heavy"),
    fontVariant: ["tabular-nums"],
    textAlign: "right",
  },
  purchaseAmountPending: {
    color: colors.accent,
  },
  purchaseAmountCharged: {
    color: colors.warmText,
  },
  viewAllButton: {
    minHeight: 44,
    borderRadius: radius.lg,
    backgroundColor: colors.rowSurface,
    paddingHorizontal: spacing.md + 2,
    paddingVertical: spacing.sm + 2,
    marginBottom: spacing.section,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    minWidth: 132,
  },
  viewAllButtonText: {
    color: colors.accentDark,
    fontSize: fontSize.body,
    ...fontStyle("bold"),
  },
  viewAllButtonMeta: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("semibold"),
  },
  cycleSummaryCard: {
    backgroundColor: colors.card,
    borderRadius: radius.sm,
    padding: spacing.md + 2,
    marginBottom: spacing.md,
    ...shadows.subtle,
  },
  cycleAmount: {
    fontSize: 34,
    lineHeight: 40,
    ...fontStyle("heavy"),
    color: colors.text,
    marginTop: 8,
  },
  noteCard: {
    backgroundColor: colors.warm,
    borderRadius: radius.sm,
    padding: spacing.md + 2,
    marginTop: spacing.xs,
    marginBottom: spacing.xxl,
  },
  noteTitle: {
    fontSize: 17,
    ...fontStyle("semibold"),
    color: colors.text,
    marginBottom: 6,
  },
  helpText: {
    color: colors.muted,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  itemCopy: {
    flex: 1,
    minWidth: 0,
  },
  itemTitle: {
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("semibold"),
    color: colors.text,
  },
  rowMetaText: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    marginTop: 2,
  },
  itemAmount: {
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("heavy"),
    color: colors.text,
    flexShrink: 0,
  },
  importIncomeAmount: {
    color: colors.accent,
  },
  itemAmountStack: {
    alignItems: "flex-end",
    gap: spacing.xs,
    flexShrink: 0,
  },
  importGroupHeader: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("bold"),
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.xs,
  },
  importReviewPanel: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginTop: spacing.section,
    marginBottom: spacing.lg,
    ...shadows.card,
  },
  importReviewTitle: {
    color: colors.text,
    fontSize: fontSize.sectionCompact,
    ...fontStyle("bold"),
    marginBottom: spacing.xs,
  },
  importReviewActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginTop: spacing.md,
    justifyContent: "flex-end",
  },
  importReviewMessage: {
    color: colors.muted,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    marginBottom: spacing.md,
  },
  importPrivacyNote: {
    color: colors.warmText,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.body,
    marginTop: spacing.sm,
  },
  importSuggestionListGroup: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    overflow: "hidden",
    marginBottom: spacing.lg,
    ...shadows.card,
  },
  importSuggestionRow: {
    minHeight: 72,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  importSuggestionRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: surfaces.divider,
  },
  importSuggestionTitleRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  importSuggestionAmountColumn: {
    alignItems: "flex-end",
    gap: spacing.xs,
    flexShrink: 0,
  },
  importSuggestionAmount: {
    color: colors.warningText,
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("bold"),
    fontVariant: ["tabular-nums"],
    textAlign: "right",
  },
  importSuggestionMeta: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight,
    ...fontStyle("medium"),
  },
  importStatusCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...shadows.subtle,
  },
  importLoadingCard: {
    alignItems: "center",
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    gap: spacing.sm,
    marginBottom: spacing.lg,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.xxl,
    ...shadows.subtle,
  },
  importLoadingOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    backgroundColor: "rgba(246, 243, 234, 0.88)",
    borderRadius: radius.sheet,
    justifyContent: "center",
    padding: spacing.xl,
    zIndex: 20,
  },
  importLoadingModalBackdrop: {
    alignItems: "center",
    backgroundColor: "rgba(11, 31, 51, 0.28)",
    flex: 1,
    justifyContent: "center",
    padding: spacing.xl,
  },
  importLoadingOverlayCard: {
    marginBottom: 0,
    width: "100%",
  },
  importLoadingSpinnerWrap: {
    alignItems: "center",
    height: 56,
    justifyContent: "center",
    marginBottom: spacing.sm,
    width: 56,
  },
  importLoadingPulseRing: {
    backgroundColor: colors.accentLight,
    borderRadius: 28,
    height: 56,
    position: "absolute",
    width: 56,
  },
  importLoadingTitle: {
    color: colors.text,
    fontSize: fontSize.bodyLg,
    ...fontStyle("bold"),
    textAlign: "center",
  },
  importLoadingSubtitle: {
    color: colors.muted,
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    textAlign: "center",
  },
  importLoadingDotsRow: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  importLoadingDot: {
    backgroundColor: colors.accent,
    borderRadius: 4,
    height: 8,
    width: 8,
  },
  statusText: {
    marginTop: 12,
    color: colors.accentDark,
    ...fontStyle("semibold"),
  },
  statusPill: {
    alignSelf: "flex-start",
    borderRadius: radius.pill,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.xs + 1,
    minHeight: 24,
    justifyContent: "center",
  },
  statusPillMenu: {
    marginTop: spacing.sm + 1,
  },
  statusPillText: {
    fontSize: fontSize.caption,
    ...fontStyle("bold"),
    letterSpacing: 0.2,
    lineHeight: lineHeight.tight - 2,
  },
  statusPillAccent: {
    backgroundColor: colors.accentLight,
  },
  statusPillTextAccent: {
    color: colors.accentDark,
  },
  statusPillNeutral: {
    backgroundColor: colors.soft,
  },
  statusPillTextNeutral: {
    color: colors.warmText,
  },
  statusPillWarning: {
    backgroundColor: colors.warning,
  },
  statusPillTextWarning: {
    color: colors.warningText,
  },
  statusPillMuted: {
    backgroundColor: colors.rowSurface,
  },
  statusPillTextMuted: {
    color: colors.muted,
  },
  statusPillWarm: {
    backgroundColor: colors.warm,
  },
  statusPillTextWarm: {
    color: colors.warningText,
  },
  rowMetaLine: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: spacing.sm - 2,
    marginTop: 2,
  },
  rowMetaDivider: {
    color: colors.muted,
    fontSize: fontSize.meta,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: colors.accent,
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 14,
  },
  secondaryButtonText: {
    color: colors.accentDark,
    ...fontStyle("semibold"),
  },
  breakdownRow: {
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  compactBreakdownRow: {
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  paycheckMetricRow: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  paycheckProjectionTotalRow: {
    marginTop: 12,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: colors.accentLight,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  paycheckProjectionTotalRowPrimary: {
    marginTop: spacing.sm,
    paddingTop: spacing.md + 2,
    borderTopWidth: 1,
    borderTopColor: surfaces.dividerWarm,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: spacing.md,
  },
  paycheckProjectionTotalLabel: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("semibold"),
    flex: 1,
  },
  paycheckProjectionTotalValue: {
    color: colors.accentDark,
    fontSize: fontSize.title + 1,
    ...fontStyle("bold"),
    fontVariant: ["tabular-nums"],
  },
  paycheckProjectionBreakdown: {
    gap: spacing.xs,
    paddingTop: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
  },
  paycheckProjectionBreakdownHelp: {
    color: colors.muted,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight + 2,
  },
  paycheckProjectionCredit: {
    color: colors.accentDark,
  },
  paycheckProjectionDeduction: {
    color: colors.text,
  },
  paycheckCoveredBillsToggle: {
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
    alignItems: "center",
    minHeight: 36,
    justifyContent: "center",
  },
  paycheckBreakdownCaret: {
    color: colors.muted,
    fontSize: fontSize.title,
    lineHeight: lineHeight.body,
    ...fontStyle("bold"),
  },
  paycheckConfirmReceivedButton: {
    alignSelf: "stretch",
    minHeight: 40,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.accentLight,
    alignItems: "center",
    justifyContent: "center",
    marginTop: spacing.md,
  },
  paycheckAdditionalIncomeContent: {
    flex: 1,
    minWidth: 0,
    gap: spacing.sm,
  },
  breakdownLabel: {
    color: colors.muted,
    fontSize: fontSize.label,
  },
  breakdownValue: {
    color: colors.text,
    fontSize: fontSize.body,
    ...fontStyle("semibold"),
  },
  inputLabel: {
    color: colors.text,
    fontSize: fontSize.label,
    ...fontStyle("semibold"),
    marginBottom: spacing.sm - 2,
    marginTop: spacing.sm - 2,
  },
  input: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: surfaces.cardBorderSoft,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md + 2,
    paddingVertical: spacing.md - 1,
    fontSize: fontSize.bodyLg,
    marginBottom: spacing.sm - 2,
    ...fontStyle("regular"),
  },
  purchaseInput: {
    paddingVertical: spacing.sm + 1,
    marginBottom: spacing.sm,
  },
  purchaseAmountHeroInput: {
    fontSize: fontSize.displaySm,
    lineHeight: lineHeight.displaySm,
    ...fontStyle("heavy"),
    textAlign: "center",
    paddingVertical: spacing.md,
  },
  purchaseRecentMerchantRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  textArea: {
    height: 110,
    textAlignVertical: "top",
  },
  readOnlyField: {
    backgroundColor: colors.soft,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md + 2,
    paddingVertical: spacing.md,
    marginBottom: spacing.sm,
  },
  readOnlyText: {
    color: colors.text,
    fontSize: fontSize.bodyLg,
    ...fontStyle("medium"),
  },
  segmentedControl: {
    flexDirection: "row",
    backgroundColor: colors.soft,
    borderRadius: radius.sm,
    padding: spacing.xs - 1,
    marginBottom: spacing.md,
  },
  segmentedControlOption: {
    flex: 1,
    minHeight: 38,
    borderRadius: radius.sm - 2,
    alignItems: "center",
    justifyContent: "center",
  },
  segmentedControlOptionActive: {
    backgroundColor: colors.card,
    ...shadows.subtle,
  },
  segmentedControlText: {
    color: colors.muted,
    fontSize: fontSize.body,
    ...fontStyle("semibold"),
  },
  segmentedControlTextActive: {
    color: colors.accentDark,
    ...fontStyle("bold"),
  },
  datePickerFrame: {
    minHeight: 220,
    justifyContent: "center",
    marginBottom: spacing.md,
  },
  datePicker: {
    height: 220,
    width: "100%",
  },
  calendarHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
    marginBottom: spacing.sm + 2,
  },
  calendarNavButton: {
    width: 38,
    height: 34,
    borderRadius: radius.pill,
    borderWidth: 0,
    borderColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  calendarNavText: {
    color: colors.accentDark,
    fontSize: 28,
    lineHeight: 30,
    ...fontStyle("regular"),
  },
  calendarMonthText: {
    flex: 1,
    color: colors.text,
    fontSize: fontSize.bodyLg,
    ...fontStyle("bold"),
    textAlign: "center",
  },
  calendarQuickChips: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.sm + 2,
    marginBottom: spacing.md,
  },
  calendarQuickChip: {
    minHeight: 34,
    paddingHorizontal: spacing.md + 1,
    borderRadius: radius.lg + 4,
    backgroundColor: colors.rowSurface,
    alignItems: "center",
    justifyContent: "center",
  },
  calendarQuickChipSelected: {
    backgroundColor: colors.accentLight,
  },
  calendarQuickChipText: {
    color: colors.muted,
    fontSize: fontSize.label,
    ...fontStyle("semibold"),
  },
  calendarQuickChipTextSelected: {
    color: colors.accentDark,
    ...fontStyle("bold"),
  },
  calendarGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: spacing.md,
  },
  calendarWeekday: {
    width: `${100 / 7}%`,
    color: colors.muted,
    fontSize: fontSize.caption,
    ...fontStyle("bold"),
    textAlign: "center",
    paddingBottom: spacing.xs + 1,
  },
  calendarDay: {
    width: `${100 / 7}%`,
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: spacing.xs - 2,
  },
  calendarDayInner: {
    width: spacing.xxxl,
    height: spacing.xxxl,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "transparent",
  },
  calendarDaySelected: {
    backgroundColor: colors.accent,
  },
  calendarDayToday: {
    borderColor: colors.accentLight,
    backgroundColor: colors.card,
  },
  calendarDayText: {
    color: colors.text,
    fontSize: fontSize.body,
    lineHeight: lineHeight.tight + 1,
    ...fontStyle("medium"),
    textAlign: "center",
    includeFontPadding: false,
  },
  calendarDaySelectedText: {
    color: colors.onAccent,
    ...fontStyle("bold"),
  },
  calendarDayTodayText: {
    color: colors.accentDark,
    ...fontStyle("bold"),
  },
  calendarDoneButton: {
    backgroundColor: colors.accent,
    paddingVertical: spacing.md,
    borderRadius: radius.sm,
    alignItems: "center",
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.accentDark,
  },
  errorText: {
    color: colors.warningText,
    fontSize: fontSize.body,
    ...fontStyle("medium"),
    marginTop: spacing.xs - 2,
    marginBottom: spacing.sm + 2,
  },
  successText: {
    color: colors.accentDark,
    fontSize: fontSize.label,
    ...fontStyle("medium"),
    lineHeight: lineHeight.tight + 1,
    marginTop: spacing.sm - 2,
  },
  keyboardAccessory: {
    backgroundColor: colors.card,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.md + 2,
    paddingVertical: spacing.sm,
    alignItems: "flex-end",
  },
  keyboardDoneButton: {
    minHeight: 36,
    paddingHorizontal: spacing.md + 2,
    borderRadius: radius.sm,
    alignItems: "center",
    justifyContent: "center",
  },
  keyboardDoneText: {
    color: colors.accentDark,
    fontSize: fontSize.bodyLg,
    ...fontStyle("bold"),
  },
  emptyState: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    padding: spacing.section,
    marginBottom: spacing.section,
    ...shadows.card,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: fontSize.title,
    ...fontStyle("semibold"),
    marginBottom: spacing.sm - 2,
  },
  emptyStateButton: {
    marginTop: spacing.md,
    alignSelf: "flex-start",
    minHeight: 44,
    borderRadius: radius.md,
    backgroundColor: colors.accent,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm + 2,
    justifyContent: "center",
  },
  emptyStateButtonText: {
    color: colors.onAccent,
    fontSize: fontSize.body,
    ...fontStyle("semibold"),
  },
  bottomNav: {
    flexDirection: "row",
    alignItems: "flex-end",
    backgroundColor: colors.card,
    borderTopWidth: 0,
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.sm + 2,
    shadowColor: colors.accentDark,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 8,
  },
  navItem: {
    flex: 1,
    alignItems: "center",
    paddingVertical: spacing.sm,
    borderRadius: radius.sm,
    gap: spacing.xs - 1,
    minHeight: 44,
  },
  navItemPrimary: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: spacing.xs,
    marginTop: -spacing.lg,
    gap: spacing.xs,
    minHeight: 72,
  },
  navItemPrimaryButton: {
    width: 58,
    height: 58,
    borderRadius: radius.fab,
    backgroundColor: colors.accentLight,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
    ...shadows.fab,
  },
  navItemPrimaryButtonActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accentDark,
  },
  navItemActive: {
    backgroundColor: colors.accentLight,
  },
  navText: {
    fontSize: 10,
    color: colors.muted,
    ...fontStyle("semibold"),
  },
  navTextActive: {
    color: colors.accentDark,
  },
  navTextPrimary: {
    fontSize: 11,
    color: colors.muted,
    ...fontStyle("bold"),
  },
  navTextPrimaryActive: {
    color: colors.accentDark,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.25)",
  },
  modalBackdrop: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  sheet: {
    backgroundColor: colors.card,
    overflow: "hidden",
    position: "relative",
    padding: spacing.xl + 2,
    borderTopLeftRadius: radius.sheet,
    borderTopRightRadius: radius.sheet,
    shadowColor: colors.accentDark,
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 10,
  },
  sheetScrollable: {
    maxHeight: "88%",
    padding: 0,
  },
  sheetScrollContent: {
    padding: spacing.xl + 2,
  },
  sheetDragHandleRow: {
    alignItems: "center",
    paddingTop: spacing.sm + 2,
    paddingBottom: spacing.xs,
  },
  sheetDragHandle: {
    width: 36,
    height: 4,
    borderRadius: radius.pill,
    backgroundColor: colors.border,
  },
  onboardingSheetTall: {
    maxHeight: "88%",
  },
  actionMenuOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.22)",
  },
  actionMenuSheet: {
    backgroundColor: colors.card,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md + 2,
    borderTopLeftRadius: radius.sheet + 4,
    borderTopRightRadius: radius.sheet + 4,
    shadowColor: colors.accentDark,
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.14,
    shadowRadius: 20,
    elevation: 12,
  },
  actionMenuHeader: {
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: surfaces.divider,
    marginBottom: spacing.xs - 1,
  },
  actionMenuHeaderTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.md + 2,
  },
  actionMenuTitle: {
    color: colors.text,
    fontSize: fontSize.title,
    ...fontStyle("bold"),
  },
  actionMenuHeaderMeta: {
    color: colors.muted,
    fontSize: fontSize.label,
    ...fontStyle("medium"),
    marginTop: spacing.xs,
  },
  actionMenuHeaderAmount: {
    color: colors.text,
    fontSize: fontSize.title + 1,
    ...fontStyle("heavy"),
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  actionMenuItem: {
    minHeight: 48,
    borderTopWidth: 1,
    borderTopColor: surfaces.divider,
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  actionMenuDangerItem: {
    marginTop: spacing.sm,
    borderTopColor: surfaces.dividerWarm,
  },
  actionMenuIcon: {
    width: 32,
    height: 32,
    borderRadius: radius.sm - 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.soft,
  },
  actionMenuDangerIcon: {
    backgroundColor: colors.warning,
  },
  actionMenuIconText: {
    color: colors.accentDark,
    fontSize: fontSize.body,
    ...fontStyle("bold"),
    lineHeight: lineHeight.tight,
  },
  actionMenuItemText: {
    color: colors.accentDark,
    fontSize: fontSize.bodyLg,
    ...fontStyle("semibold"),
  },
  actionMenuErrorText: {
    color: colors.warningText,
    fontSize: fontSize.meta,
    lineHeight: lineHeight.tight - 1,
    marginTop: spacing.sm - 2,
  },
  actionMenuDangerText: {
    color: colors.warningText,
  },
  actionMenuCancel: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    marginTop: spacing.sm,
  },
  actionMenuCloseText: {
    color: colors.muted,
    ...fontStyle("semibold"),
    fontSize: fontSize.bodyLg,
  },
  overflowButton: {
    width: 28,
    height: 26,
    borderRadius: radius.sm - 2,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.soft,
  },
  overflowButtonText: {
    color: colors.accentDark,
    fontSize: fontSize.bodyLg,
    lineHeight: lineHeight.body,
    ...fontStyle("bold"),
    marginTop: -5,
  },
  cancelButton: {
    alignItems: "center",
    paddingVertical: spacing.md + 2,
  },
  cancelButtonText: {
    color: colors.muted,
    ...fontStyle("semibold"),
    fontSize: fontSize.bodyLg,
  },
  settingsMoneyCard: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginBottom: spacing.section,
    ...shadows.card,
  },
  settingsMoneySection: {
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  settingsMetricRow: {
    flexDirection: "row",
    backgroundColor: colors.rowSurface,
    borderRadius: radius.md,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.lg,
    marginTop: spacing.sm,
  },
  settingsMetric: {
    flex: 1,
    alignItems: "center",
    gap: spacing.xs,
  },
  settingsMetricDivider: {
    width: 1,
    alignSelf: "stretch",
    backgroundColor: surfaces.divider,
  },
  settingsMetricLabel: {
    color: colors.muted,
    fontSize: fontSize.caption,
    ...fontStyle("semibold"),
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  settingsMetricValue: {
    color: colors.text,
    fontSize: fontSize.bodyLg,
    ...fontStyle("bold"),
    fontVariant: ["tabular-nums"],
  },
  settingsSectionHeader: {
    marginBottom: spacing.sm + 2,
    marginTop: spacing.xs,
  },
  settingsPreferenceGroup: {
    backgroundColor: surfaces.card,
    borderRadius: radius.lg,
    marginBottom: spacing.section,
    overflow: "hidden",
    ...shadows.card,
  },
  settingsPreferenceRow: {
    minHeight: 72,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  settingsAppearanceControl: {
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.md,
  },
  settingsPreferenceDivider: {
    borderBottomWidth: 1,
    borderBottomColor: surfaces.divider,
  },
  settingsSaveButton: {
    marginTop: spacing.md,
  },
  settingsGroupTitle: {
    color: colors.muted,
    fontSize: fontSize.meta,
    ...fontStyle("bold"),
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: spacing.sm - 2,
    marginTop: spacing.xs - 2,
  },
  settingsRow: {
    padding: spacing.md + 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  settingsValue: {
    color: colors.accentDark,
    fontSize: fontSize.body,
    ...fontStyle("semibold"),
  },
  settingsInlineControl: {
    alignItems: "flex-end",
    gap: spacing.sm - 1,
    flexShrink: 0,
  },
  settingsActionColumn: {
    alignItems: "flex-end",
    gap: spacing.sm - 1,
    flexShrink: 0,
  },
  settingsActionButton: {
    minHeight: 36,
    paddingHorizontal: spacing.md + 2,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.accentLight,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  settingsActionButtonText: {
    color: colors.accentDark,
    fontSize: fontSize.label,
    ...fontStyle("bold"),
  },
  disabledAction: {
    opacity: 0.55,
  },
  fab: {
    position: "absolute",
    right: spacing.xl + 2,
    width: 56,
    height: 56,
    borderRadius: radius.fab,
    backgroundColor: colors.accent,
    borderWidth: 1,
    borderColor: colors.accentDark,
    alignItems: "center",
    justifyContent: "center",
    ...shadows.fab,
  },
  fabPressable: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  fabText: {
    color: colors.onAccent,
    fontSize: fontSize.label + 2,
    ...fontStyle("bold"),
  },
  pressed: {
    opacity: 0.72,
  },
  });
}

export type AppStyles = ReturnType<typeof createStyles>;

/** Static light-theme exports for tests and non-React modules. */
export const colors = lightTheme.colors;
export const surfaces = lightTheme.surfaces;
export const shadows = createShadows(lightTheme);
export const styles = createStyles(lightTheme);
